name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
    
      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
        
      - name: yarn build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
          
      - name: upload package to aliyun
        uses: appleboy/scp-action@v0.0.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.ssh_privatekey }}
          passphrase: ${{ secrets.ssh_passphrase }}
          source: "build/*"
          target: "/var/www/wevid_website"
          rm: true
          strip_components: 1
